---
- name: Check AAP controller metrics
  hosts: localhost
  connection: local
  vars:
    controller_host: '{{ lookup("env", "CONTROLLER_HOST") }}'
    controller_username: '{{ lookup("env", "CONTROLLER_USERNAME") }}'
    controller_oauth_token: '{{ lookup("env", "CONTROLLER_OAUTH_TOKEN") | default(omit) }}'
    controller_password: '{{ lookup("env", "CONTROLLER_PASSWORD") | default(omit) }}'
    controller_verify_ssl: '{{ lookup("env", "CONTROLLER_VERIFY_SSL") }}'
  tasks:

    - name: Get the status from the API call
      ansible.builtin.set_fact:
        controller_metrics: "{{ lookup('ansible.controller.controller_api', 'metrics/?format=json', host=controller_host,
                              username=controller_user, oauth_token=controller_oauth_token, verify_ssl=false) }}"

    - name: Display AAP controller API endpoint contents
      ansible.builtin.debug:
        msg: "{{ controller_metrics }}"
...
