---
- name: Create an activation key in Red Hat Satellite
  hosts: localhost
  connection: local
  tasks:

    - name: Create an activation key
      redhat.satellite.activation_key:
        username: "admin"
        password: "changeme"
        server_url: "https://satellite.example.com"
        name: "edge"
        organization: "Default Organization"
        lifecycle_environment: "Library"
        content_view: 'edge content view'
        host_collections:
          - rhel9-edge
        auto_attach: true
        release_version: 9.2
        service_level: Premium
...
