---
- name: Random plaintext password
  hosts: localhost
  connection: local
  vars:
    my_password: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits'], length=12) }}"
  tasks:

    - name: Show password
      ansible.builtin.debug:
        msg: "{{ my_password }}"
...
