---
- name: Get the amount of hosts
  hosts: localhost
  connection: local
  vars:
    controller_host: '{{ lookup("env", "CONTROLLER_HOST") }}'
    controller_username: '{{ lookup("env", "CONTROLLER_USERNAME") }}'
    controller_oauth_token: '{{ lookup("env", "CONTROLLER_OAUTH_TOKEN") | default(omit) }}'
    controller_password: '{{ lookup("env", "CONTROLLER_PASSWORD") | default(omit) }}'
    controller_verify_ssl: '{{ lookup("env", "CONTROLLER_VERIFY_SSL") }}'
    inventory_id: 2
  tasks:

    - name: Set the amount of hosts from an inventory as a fact
      ansible.builtin.set_fact:
        inventory_hosts: "{{ query('ansible.controller.controller_api', 'inventories/{{ inventory_id }}')
                            | map(attribute='total_hosts') }}"

    - name: Display the amount of hosts in an inventory
      ansible.builtin.debug:
        msg: "{{ inventory_hosts }}"
...
