---
- name: Password hash
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Generate a password hash
      ansible.builtin.debug:
        msg: "{{ 'RedHat!' | password_hash }}"
...
