---
- name: Reboot system is a reboot is required
  hosts: all
  become: true
  tasks:

    - name: Ensure that yum-utils is installed before upgrading packages
      ansible.builtin.yum:
        name: yum-utils
        state: present

    - name: Upgrade all packages
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_only: true

    - name: Check if an upgrade is required for RHEL 7, 8, and 9
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version > '6'
      block:

        - name: Check if an upgrade is required
          ansible.builtin.command: /usr/bin/needs-restarting -r
          register: reboot_required
          failed_when: reboot_required.rc not in (0, 1)
          changed_when: reboot_required.rc == 1

        - name: Reboot system if kernel was updated
          ansible.builtin.reboot:
          when:
            - reboot_required.rc == 1

    - name: Check if an upgrade is required for RHEL 6
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version == '6'
      block:

        - name: Check if an upgrade is required
          ansible.builtin.command: /usr/bin/needs-restarting
          register: reboot_required
          failed_when: reboot_required_rhel6.rc not in (0, 1)
          changed_when: reboot_required_rhel6.rc == 1

        - name: Reboot system if kernel was updated
          ansible.builtin.reboot:
          when:
            - reboot_required.rc == 1
...
